export type StudioVoice = { id: string; label: string; hint: string };

export const STUDIO_VOICES: StudioVoice[] = [
  { id: "TX3LPaxmHKxFdv7VOQHJ", label: "Liam", hint: "UGC · social" },
  { id: "kPzsL2i3teMYv0FxEYQ6", label: "Brittney", hint: "Fun · youthful" },
  { id: "N2lVS1w4EtoT3dr4eOWO", label: "Callum", hint: "Husky" },
  { id: "FGY2WhTYpPnrIDTdsKH5", label: "Laura", hint: "Quirky" },
  { id: "EkK5I93UQWFDigLMpZcX", label: "James", hint: "Bold" },
  { id: "BZgkqPqms7Kj9ulSkVzn", label: "Eve", hint: "Energetic" },
  { id: "5l5f8iK3YPeGga21rQIX", label: "Adeline", hint: "Conversational" },
  { id: "aD6riP1btT197c6dACmy", label: "Rachel M", hint: "British radio" },
  { id: "nPczCjzI2devNBz1zQrb", label: "Brian", hint: "Deep" },
  { id: "hpp4J3VqNfWAUOO0d1Us", label: "Bella", hint: "Warm pro" },
  { id: "Z3R5wn05IrDiVCyEkUrK", label: "Arabella", hint: "Mysterious" },
  { id: "NNl6r8mD7vthiJatiJt1", label: "Bradford", hint: "Articulate" },
  { id: "YOq2y2Up4RgXP2HyXjE5", label: "Xavier", hint: "Announcer" },
  { id: "B8gJV1IhpuegLxdpXFOE", label: "Kuon", hint: "Cheerful" },
  { id: "2zRM7PkgwBPiau2jvVXc", label: "Monika Sogam", hint: "Deep natural" },
  { id: "1SM7GgM6IMuvQlz2BwM3", label: "Mark", hint: "Casual" },
  { id: "scOwDtmlUjD3prqpp97I", label: "Sam", hint: "Support" },
  { id: "NOpBlnGInO9m6vDvFkFC", label: "Spuds Oxley", hint: "Wise" },
  { id: "wo6udizrrtpIxWGp2qJk", label: "Northern Terry", hint: "UK north" },
  { id: "gU0LNdkMOQCOrPrwtbee", label: "British Football Announcer", hint: "Stadium" },
  { id: "DGzg6RaUqxGRTHSBjfgF", label: "Brock", hint: "Commanding" },
  { id: "x70vRnQBMBu4FAYhjJbO", label: "Nathan", hint: "Radio host" },
  { id: "Sm1seazb4gs7RSlUVw7c", label: "Anika", hint: "Animated" },
  { id: "P1bg08DkjqiVEzOn76yG", label: "Viraj", hint: "Rich soft" },
  { id: "qDuRKMlYmrm8trt5QyBn", label: "Taksh", hint: "Calm smooth" },
  { id: "qXpMhyvQqiRxWQs4qSSB", label: "Horatius", hint: "Character" },
  { id: "UgBBYS2sOqTuMpoF3BR0", label: "Mark", hint: "Natural chat" },
  { id: "uYXf8XasLslADfZ2MB4u", label: "Hope", hint: "Bubbly" },
  { id: "gs0tAILXbY5DNrJrsM6F", label: "Jeff", hint: "Classy" },
  { id: "DTKMou8ccj1ZaWGBiotd", label: "Jamahal", hint: "Young vibrant" },
  { id: "vBKc2FfBKJfcZNyEt1n6", label: "Finn", hint: "Youthful" },
  { id: "DYkrAHD8iwork3YSUBbs", label: "Tom", hint: "Books" },
  { id: "56AoDkrOh6qfVPDXZ7Pt", label: "Cassidy", hint: "Crisp" },
  { id: "eR40ATw9ArzDf9h3v7t7", label: "Addison 2.0", hint: "Australian" },
  { id: "g6xIsTj2HwM6VR4iXFCw", label: "Jessica Anne Bogart", hint: "Chatty" },
  { id: "lcMyyd2HUfFzxdCaC4Ta", label: "Lucy", hint: "Fresh casual" },
  { id: "6aDn1KB0hjpdcocrUkmq", label: "Tiffany", hint: "Welcoming" },
  { id: "Sq93GQT4X1lKDXsQcixO", label: "Felix", hint: "Warm RP" },
  { id: "flHkNRp1BlvT73UL6gyz", label: "Jessica Anne Bogart", hint: "Villain" },
  { id: "9yzdeviXkFddZ4Oz8Mok", label: "Lutz", hint: "Cheerful" },
  { id: "pPdl9cQBQq4p6mRkZy2Z", label: "Emma", hint: "Upbeat" },
  { id: "zYcjlYFOd3taleS0gkk3", label: "Edward", hint: "Confident" },
  { id: "nzeAacJi50IvxcyDnMXa", label: "Marshal", hint: "Funny professor" },
  { id: "ruirxsoakN0GWmGNIo04", label: "John Morgan", hint: "Cowboy" },
  { id: "TC0Zp7WVFzhA8zpTlRqV", label: "Aria", hint: "Sultry" },
  { id: "ljo9gAlSqKOvF6D8sOsX", label: "Viking Bjorn", hint: "Epic" },
  { id: "PPzYpIqttlTYA83688JI", label: "Pirate Marshal", hint: "Pirate" },
  { id: "8JVbfL6oEdmuxKn5DK2C", label: "Johnny Kid", hint: "Narrator" },
  { id: "iCrDUkL56s3C8sCRl7wb", label: "Hope", hint: "Poetic" },
  { id: "wJqPPQ618aTW29mptyoc", label: "Ana Rita", hint: "Expressive" },
  { id: "EiNlNiXeDU1pqqOPrYMO", label: "John Doe", hint: "Deep" },
  { id: "4YYIPFl9wE5c4L2eu2Gb", label: "Burt Reynolds", hint: "Smooth" },
  { id: "6F5Zhi321D3Oq7v1oNT4", label: "Hank", hint: "Narrator" },
  { id: "YXpFCvM1S3JbWEJhoskW", label: "Wyatt", hint: "Rustic" },
  { id: "LG95yZDEHg6fCZdQjLqj", label: "Phil", hint: "Announcer" },
  { id: "CeNX9CMwmxDxUF5Q2Inm", label: "Johnny Dynamite", hint: "Vintage radio" },
  { id: "mtrellq69YZsNwzUSyXh", label: "Rex Thunder", hint: "Tough" },
  { id: "dHd5gvgSOzSfduK4CvEg", label: "Ed", hint: "Late night" },
  { id: "eVItLK1UvXctxuaRV2Oq", label: "Jean", hint: "Playful" },
  { id: "esy0r39YPLQjOczyOib8", label: "Britney", hint: "Calm villain" },
  { id: "Tsns2HvNFKfGiNjllgqo", label: "Sven", hint: "Emotional" },
  { id: "1U02n4nD6AdIZ9CjF053", label: "Viraj", hint: "Gentle" },
  { id: "AeRdCCKzvd23BpJoofzx", label: "Nathaniel", hint: "British calm" },
  { id: "LruHrtVF6PSyGItzMNHS", label: "Benjamin", hint: "Warm" },
  { id: "1wGbFxmAM3Fgw63G1zZJ", label: "Allison", hint: "Soothing" },
  { id: "hqfrgApggtO1785R4Fsn", label: "Theodore HQ", hint: "Serene" },
  { id: "MJ0RnG71ty4LH3dvNfSd", label: "Leon", hint: "Grounded" },
];

export function voicePreviewUrl(id: string) {
  return `https://static.aiquickdraw.com/elevenlabs/voice/${id}.mp3`;
}
